# Usa la imagen de PHP con Apache
FROM php:8.1-apache

# Copia los archivos de tu proyecto al contenedor
COPY . /var/www/html/

# Habilita los módulos necesarios y configura el servidor
RUN docker-php-ext-install pdo pdo_mysql

# Expone el puerto 80
EXPOSE 80
