services:
  - name: php-app
    type: web
    env: docker
    plan: free
    repo: https://github.com/josechirinos11/proyectoCEAC
    branch: main
    rootDir: /
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        value: TU_HOST_DE_CLEVER_CLOUD
      - key: DB_NAME
        value: TU_BASE_DE_DATOS
      - key: DB_USER
        value: TU_USUARIO
      - key: DB_PASS
        value: TU_CONTRASEÑA
      - key: DB_PORT
        value: "3306"
