services:
  - type: pserv
    name: mysql
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 1
  - type: web
    name: soluciones_integrales
    runtime: php  # Cambiado de "env" a "runtime"
    plan: free
    rootDir: public
    startCommand: "php -S 0.0.0.0:8000 index.php"  # Agregado explícitamente
    envVars:
      - key: DB_HOST
        fromService:
          type: pserv
          name: mysql
          property: host
      - key: DB_NAME
        value: soluciones_integrales
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: 01200300